name : Strength in Numbers
tagline: Xiaofei-Wang.com
author : Xiaofei Wang
author_email : xiaofei.wang@yale.edu

production_url : http://xiaofei-wang.com/
baseurl: /xiaofei-wang.github.com

auto : false
