name : Xiaofei (Susan) Wang Homepage
tagline: 
author : 
author_email : 

production_url : http://swang87.github.io/
baseurl: http://swang87.github.io

auto : false
google_analytics_code: UA-42671518-1
google_analytics_domain: xiaofei-wang.com
