name : Xiaofei-Wang.com
tagline: Xiaofei-Wang.com
author : Xiaofei Wang
author_email : swang@amherst.edu

production_url : http://xiaofei-wang.com/
baseurl: http://xiaofei-wang.com

auto : false
google_analytics_code: UA-42671518-1
google_analytics_domain: xiaofei-wang.com
