---
title: "Doctors and Hospitals II (Use)"
author: ""
date: "Last Updated: Jan 27, 2015"
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r include=FALSE}
# Don't delete this chunk if you are using the mosaic package
# This loads the mosaic and dplyr packages
require(mosaic)
```

```{r include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).

# This changes the default colors in lattice plots.
trellis.par.set(theme=theme.mosaic())  

# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
# This loads the mosaic data sets.  (Could be deleted if you are not using them.)
require(mosaicData)    
require(Stat2Data)
```

This exercise corresponds to the second part of Example 1.6 beginning on p.42 of the text.

```{r}
data(MetroHealth83)
```

## Recap

Our second shot at a model is the following:

```{r}
m2 <- lm(sqrt(NumMDs) ~ NumHospitals, data=MetroHealth83)
summary(m2)
```

$$ \widehat{\sqrt{numMDs}} = 14.03 + 2.91NumHospitals$$

The Assess step showed that this model satisfies the assumptions of a linear regression model. Let's proceed to make a prediction.

## Prediction

Predict the number of MDs in Louisville, KY, which has 18 community hospitals.

SOLUTION:

```{r}
predictMDs <- makeFun(m2)
predictMDs(NumHospitals = 18)^2
```

